# Use Golang image
FROM golang:1.19-alpine

# Set working directory
WORKDIR /app

# Copy server code
COPY ./server /app

# Install dependencies and build the server
RUN go mod tidy
RUN go build -o chatserver ./cmd/chatserver

# Expose the port the server will run on
EXPOSE 8080

# Command to run the server
CMD ["./chatserver"]
