# Use Golang image
FROM golang:1.19-alpine

# Set working directory
WORKDIR /app

# Copy client code
COPY ./client /app

# Install dependencies and build the client
RUN go mod tidy
RUN go build -o chatclient ./cmd/chatclient

# Command to run the client (it will automatically run once the container starts)
CMD ["./chatclient"]
