version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "8080:8080"
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    depends_on:
      - server
